### ISSUE TITLE
Would you mind adding a warning for delete button at questions page 

### ISSUE THREAD

**Issue by gurjyot** [amiyasahu/q2a-delete-hidden-posts#2]
The plugin works perfect but it happened with me today that I accidentally hit the delete button and the Question with all its answers is gone. Well the plugin did what it is made to do. But now I realize that it would be better if a warning is added so that warning message pops but whenever the delete button is hit from the Question page.
No need for warning in hidden section bcoz most of the time we go there to delete questions only. 
Need to know your view on this.

**Comment by amiyasahu** [comment]
Fixed
